### ISSUE TITLE
Example for seq, labels & chromatin track

### ISSUE THREAD

**Issue by tuannguyen8390** [seqcode/Bichrom#3]
Hi there, 

I wonder if you can provide a small example in the current repo to run your program ?
To be precise, I am unsure of the formatting of labels & chromatin_tracks 

```
train:  
  seq: '/path/to/train/seq.txt'    
  labels: '/path/to/train/labels.txt'  
  chromatin_tracks: ['/path/to/train/atacseq.txt', ..., '/path/to/train/h3k27ac.txt']  

val: 
  seq: '/path/to/val/seq.txt'  
  labels: '/path/to/val/labels.txt'  
  chromatin_tracks: ['/path/to/val/atacseq.txt', ..., '/path/to/val/h3k27ac.txt'] 

test: 
  seq: '/path/to/test/seq.txt'  
  labels: '/path/to/test/labels.txt'  
  chromatin_tracks: ['/path/to/val/atacseq.txt', ..., '/path/to/test/h3k27ac.txt'] 
```

Best,

Tuan Nguyen
